debug_mode: true
events_source: meetup
tokens:
  telegram: "TELEGRAM_TOKEN"
  facebook: "FACEBOOK_API_KEY"
  meetup_client_id: "MEETUP_CLIENT_ID"
  meetup_client_secret: "MEETUP_CLIENT_SECRET"
  meetup_refresh_token: "MEETUP_REFRESH_TOKEN"
links:
  link1: "url_1"
  link2: "url_2"
custom_responses:
  "/custom_1": "This is a custom bot command."